#!/bin/bash
if [[ $1 != 'down' ]]
then
  cd /home/bhemanth/oradbctl
tup(){
login='sys/Hemanth22 as sysdba'
sqlplus $login <<EOF
@exit.sql
EOF
 cd /home/bhemanth/Desktop
touch db_up.dat
cd -
}
tup
else
cd /home/bhemanth/Desktop
tdown(){
touch db_down.dat
cd -
}
tdown
unset tup
unset tdown
fi
